/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-tint": "#4059aa",
              "on-surface": "#131b2e",
              "outline-variant": "#c5c5d3",
              "on-background": "#131b2e",
              "primary-fixed-dim": "#b6c4ff",
              "on-tertiary-fixed": "#191c1e",
              "surface-container-low": "#f2f3ff",
              "on-primary-fixed-variant": "#264191",
              "surface-bright": "#faf8ff",
              "surface-container-high": "#e2e7ff",
              "secondary-fixed-dim": "#b7c8e1",
              "surface-variant": "#dae2fd",
              "inverse-surface": "#283044",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed-variant": "#38485d",
              "on-primary-container": "#90a8ff",
              "error-container": "#ffdad6",
              "surface-container-highest": "#dae2fd",
              "on-secondary-fixed": "#0b1c30",
              "surface": "#faf8ff",
              "secondary": "#505f76",
              "on-secondary": "#ffffff",
              "error": "#ba1a1a",
              "tertiary-fixed-dim": "#c4c7c9",
              "on-error": "#ffffff",
              "secondary-fixed": "#d3e4fe",
              "outline": "#757682",
              "on-surface-variant": "#444651",
              "tertiary": "#272b2d",
              "background": "#faf8ff",
              "on-primary-fixed": "#00164e",
              "on-primary": "#ffffff",
              "on-error-container": "#93000a",
              "on-tertiary-fixed-variant": "#444749",
              "tertiary-container": "#3d4143",
              "on-secondary-container": "#54647a",
              "inverse-on-surface": "#eef0ff",
              "surface-dim": "#d2d9f4",
              "surface-container-lowest": "#ffffff",
              "inverse-primary": "#b6c4ff",
              "primary-fixed": "#dce1ff",
              "tertiary-fixed": "#e0e3e5",
              "on-tertiary-container": "#aaadaf",
              "primary": "#00236f",
              "surface-container": "#eaedff",
              "secondary-container": "#d0e1fb",
              "primary-container": "#1e3a8a"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xl": "32px",
              "md": "16px",
              "unit": "4px",
              "xs": "4px",
              "lg": "24px",
              "margin-mobile": "16px",
              "gutter": "16px",
              "sm": "8px",
              "margin-desktop": "32px"
      },
      "fontFamily": {
              "headline-lg-mobile": ["Inter"],
              "title-lg": ["Inter"],
              "label-md": ["Inter"],
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "headline-sm": ["Inter"],
              "label-lg": ["Inter"],
              "code": ["Inter"],
              "title-md": ["Inter"],
              "body-md": ["Inter"],
              "headline-md": ["Inter"]
      },
      "fontSize": {
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
              "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "label-lg": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "code": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
              "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
