apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ccms
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  BatchSettings__IntervalMinutes: "15"
  AllowedHosts: "*"
  FRONTEND_API_URL: "http://ccms-backend-service/api"
  AZURE_STORAGE_CONTAINER_NAME: "case-documents"
