apiVersion: v1
kind: Service
metadata:
  name: ccms-frontend-service
  namespace: ccms
  labels:
    app: ccms-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ccms-frontend
