apiVersion: v1
kind: Secret
metadata:
  name: ccms-secrets
  namespace: ccms
type: Opaque
stringData:
  mysql-root-password: "<replace-at-deploy-time>"
  db-connection-string: "<replace-at-deploy-time>"
  jwt-secret: "<replace-at-deploy-time>"
  blob-connection-string: "<replace-at-deploy-time>"
